{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
    {{- include "redis-operator.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.service.port }}
  selector:
    {{- include "redis-operator.selectorLabels" . | nindent 4 }}
{{- end }}
