apiVersion: v1
kind: Secret
metadata:
  name: redis-cluster-auth
  namespace: default
type: Opaque
stringData:
  password: cluster-pass-123
---
apiVersion: redis.storbase.io/v1alpha1
kind: Redis
metadata:
  name: redis-cluster
  namespace: default
spec:
  mode: cluster
  image: docker.io/library/redis:8.6.1
  imagePullPolicy: IfNotPresent
  auth:
    redisPasswordSecretRef:
      name: redis-cluster-auth
      key: password
  cluster:
    shards: 3
    replicasPerShard: 1
    storage:
      size: 10Gi
