apiVersion: redis.storbase.io/v1alpha1
kind: Redis
metadata:
  name: redis-sample
spec:
  mode: Cluster
  image: docker.io/library/redis:8.6.1
  imagePullPolicy: IfNotPresent
  redisConfig:
  - save 900 1
  - save 300 10
  cluster:
    shards: 3
    replicasPerShard: 1
    storage:
      size: 10Gi
  exporter:
    enabled: false
