apiVersion: redis.storbase.io/v1alpha1
kind: Redis
metadata:
  name: redis-sample
spec:
  mode: cluster
  image: docker.io/library/redis:8.6.1
  imagePullPolicy: IfNotPresent
  # Optional TLS:
  # 1. Create a Secret in the same namespace with keys: tls.crt, tls.key, ca.crt.
  # 2. Reference that Secret here.
  # tls:
  #   secretName: redis-tls
  redisConfig:
  - save 900 1
  - save 300 10
  cluster:
    shards: 3
    replicasPerShard: 1
    storage:
      size: 10Gi
  exporter:
    enabled: false
