nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/storbase/redis-operator
  tag: v0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

metrics:
  service:
    enabled: true
    port: 8443

extraArgs: []
